region:
  name: falkland_islands
  crs: EPSG:4326

  bbox:
    xmin: -64
    ymin: -57
    xmax: -51
    ymax: -47

  buffer_km: 50


grid:
  system: H3
  resolution: 6


time:
  start: "2014-01-01"
  end: "2023-12-31"


paths:
  data: "data"
  raw: "data/raw"
  processed: "data/processed"
  grids: "data/grids"
  logs: "logs"

datasets:

  sst:
    provider: podaac
    product: MUR-JPL-L4-GLOB-v4.1
    variable: analysed_sst
    resolution: 0.01deg

  chlorophyll:
    provider: nasa_oceancolor
    product: VIIRS_SNPP_L3m_DAY_CHL
    variable: chlor_a
    transform: log10
    resolution: 4km

  ssh:
    provider: copernicus
    product: SEALEVEL_GLO_PHY_L4_MY_008_047
    variable: adt
    resolution: 0.25deg
    


layer1:
  variables:
    - sst
    - chlorophyll
    - ssh

  transforms:
    chlorophyll: log10

  standardize: true