region:
  name: falkland_islands
  crs: EPSG:4326

  bbox:
    xmin: -64
    ymin: -57
    xmax: -51
    ymax: -47

  buffer_km: 50

grid:
  system: H3
  resolution: 6

time:
  start: "2014-01-01"
  end: "2023-12-31"

paths:
  data: "data"
  raw: "data/raw"
  processed: "data/processed"
  grids: "data/grids"
  lookups: "data/lookups"
  layer1: "data/layer1"
  layer2: "data/layer2"
  models: "data/models"
  logs: "logs"
  plots: "plots"
  reference: "reference"

references:
  land: "reference/ne_10m_land/ne_10m_land.shp"
  coastline: "reference/ne_10m_coastline/ne_10m_coastline.shp"
  fisheries: "reference/fisheries_grid_squares/GridSquares.shp"
  limits: "reference/ukho_ficz_focz_limits/ukho_ficz_focz_limits.shp"

datasets:
  sst:
    provider: podaac
    product: MUR-JPL-L4-GLOB-v4.1
    variable: analysed_sst

  chl:
    provider: copernicus
    product: cmems_obs-oc_glo_bgc-plankton_my_l4-gapfree-multi-4km_P1D
    variable: CHL

  ssh:
    provider: copernicus
    product: cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.125deg_P1D
    variable: adt
    
  wind:
    provider: cds
    product: derived-era5-single-levels-daily-statistics
    variables:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind

  gfw:
    provider: gfw
  
  bathymetry:
    provider: gebco
    product: gebco_2026
    variable: elevation

downloads:
  workers: 8

layer1:
  method: mean      # mean | centroid
  variables:
    - sst
    - chl
    - ssh

  transforms:
    chl: log10

  standardize: true

gfw:
  token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtpZEtleSJ9.eyJkYXRhIjp7Im5hbWUiOiJieWNhdGNoLXJpc2tzY2FwZSIsInVzZXJJZCI6NjA0NTQsImFwcGxpY2F0aW9uTmFtZSI6ImJ5Y2F0Y2gtcmlza3NjYXBlIiwiaWQiOjc5NjUsInR5cGUiOiJ1c2VyLWFwcGxpY2F0aW9uIn0sImlhdCI6MTc3Njg5MzM5MiwiZXhwIjoyMDkyMjUzMzkyLCJhdWQiOiJnZnciLCJpc3MiOiJnZncifQ.SRLQXBLU5knquuQZ9ajya90kAL7lfTq1mRrzxdHJS42d52EouhFJ1OH8KSg864rZDkYfyfT-TuNQT0ushQk50g6YQqhtE8FQmCeV-oXIJIEhpKwBHYJkuqNPMVI6afV5xgypa7tZYZjONyWSVkCxhBFQfP64juph-Tf9xv9a7Y_2knPlBM-zlx7ojAW-i1l4KDY5CMSahWB85iHTH6S7rRcQC3eacyi2_qqJdAoZ6nzVQvQ_6AMhoRs2kmtcRQ_qWH5dlzPaPVQffdhDjUsh8Gc5OzsRyrgAXJ3d-3tWvjVgiZWdHMS_OHpyHDrZk9JgVCLAvB4bLuQ47salSo3l0wqtoxtATN82LvZjAwN-Oev20aRulJn9vWKc2jJoOX_1WVC5esEApMDdoQiLAYpDEK2YnRd1Oab0SQ_WzPOFpRtpqS-Pcfe6IlsCc8D8QfyfpymgHjtG8x7M7fBJkYmHSFYr9wNcemBa4dU-V1Qi1XoDLheZGUvYomxWd00xtzn5"
  request_delay_seconds: 65